# Generated by Django 3.2.6 on 2021-08-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('last_command', models.TextField()),
                ('last_message_id', models.IntegerField()),
                ('last_message_text', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
