# Generated by Django 3.2.6 on 2021-08-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='first_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='last_command',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='last_message_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='last_message_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='last_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
